server:
  port: 8001
  servlet:
    context-path: /account
    encoding:
      force: true
      charset: UTF-8

spring:
  application:
    name: account-server
  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/open_rana?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: LR251000@
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      client-type: lettuce
      password:
      host: 127.0.0.1
      port: 6379
      DB: 0
  web:
    resources:
      static-locations: classpath:/static/



aliyun:
  accessKeyId:
  accessKeySecret:

eureka:
  client:
    service-url:
      defaultZone: https://eureka.linergou.ink/eureka/

# thread configuration
thread:
  core-pool-size: 10
  max-pool-size: 20
  keep-alive-seconds: 60
  pool-name: DefaultThreadPool-
  queue-capacity: 200
